name: Release binary

on:
  push:
    tags: 
      - v*

jobs:
  release:
    name: Release binary
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "setup go"
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"

      - name: "goreleaser"
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"